CREATE DATABASE IF NOT EXISTS HAMBURGUER;

USE HAMBURGUER;

CREATE TABLE IF NOT EXISTS TB_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NM_USUARIO VARCHAR(200) NOT NULL,
    DS_EMAIL VARCHAR(200) NOT NULL UNIQUE,
    DS_SENHA_HASH VARCHAR(200) NOT NULL 
);

INSERT INTO TB_USUARIO (NM_USUARIO, DS_EMAIL, DS_SENHA_HASH)
VALUES ('admin', 'admin@.com.br', 'hashed_password');

SELECT ID_USUARIO, NM_USUARIO, DS_EMAIL
FROM TB_USUARIO
WHERE DS_EMAIL = 'admin@.com.br' AND DS_SENHA_HASH = 'hashed_password';
