USE HAMBURGUER;

INSERT INTO TB_USUARIO (NM_USUARIO, DS_EMAIL, DS_SENHA)
VALUES ('admin', 'admin@.com.br', 'hashed_password');

SELECT ID_USUARIO, NM_USUARIO, DS_EMAIL
FROM TB_USUARIO
WHERE DS_EMAIL = ? AND DS_SENHA = ?;